# Generated by Django 5.2.1 on 2025-06-16 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_no', models.CharField(max_length=40)),
                ('branch', models.CharField(max_length=40)),
                ('marks', models.IntegerField(max_length=80)),
            ],
        ),
    ]
